### ISSUE TITLE
Palm Trees

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/TerraOverworldConfig#10]
Palm trees either procedural and or hand built. These don't have to be super extravagant or large, and should just comprise of jungle wood (perhaps with stripped variants) + jungle leaves + possibly cocoa beans.

#### References

![image](https://user-images.githubusercontent.com/73215501/146275727-706c0993-c85b-4499-9427-9cc4758ae03c.png)

![image](https://user-images.githubusercontent.com/73215501/146275879-80bda5d1-dbac-436b-8f4c-ac017d735304.png)

![image](https://user-images.githubusercontent.com/73215501/146275982-0a282bc8-d3a5-4563-b4c1-3348a8e761dc.png)

**Comment by Sancires** [comment]
Closing as marked "Done"
