### ISSUE TITLE
Improve shale beach

### ISSUE THREAD

**Issue by astrsh** [PolyhedralDev/TerraOverworldConfig#115]
Currently the shale beach biome is pretty bland:
![image](https://user-images.githubusercontent.com/73215501/175475945-aa972617-077a-490e-88a5-b137ce002c77.png)
Adding some features, such as dead coral bushes, rocks and other fitting things would do a lot to make it feel less dead.

**Comment by Sancires** [comment]
Varied elevation, tiny pine trees, water spots, and moss should add improve these ![image](https://github.com/PolyhedralDev/TerraOverworldConfig/assets/82296481/2fd037c2-bbe0-429f-89ca-840dbeb05669)

![image](https://github.com/PolyhedralDev/TerraOverworldConfig/assets/82296481/9450ea75-19e8-4bc2-952d-6f582ab1fdd0)

**Comment by Sancires** [comment]
Added by Rogue
