### ISSUE TITLE
Kelp is only one block tall

### ISSUE THREAD

**Issue by LuciusofLegend** [PolyhedralDev/TerraOverworldConfig#129]
Naturally spawning kelp is only one block tall with the default config.  I first noticed this on my SMP, but I had a bunch of other mods, so I tested it with just terra.  Unfortunately, the issue persisted.  Just thought you'd want to know about this bug.  Awesome mod by the way!

**Comment by Astrashh** [comment]
Terra, Overworld, and server version? Kelp should generate several blocks high, here is Terra 6.2 / Overworld 1.2 / MC 1.19 
![image](https://user-images.githubusercontent.com/73215501/178127071-1595e0bf-dee6-4f93-be4a-29251ce36781.png)

**Comment by LuciusofLegend** [comment]
One thing, sorry, I was going to write the issue but not send it yet, then test it without any other mods, but I forgot.  I'll go ahead and do that, but the version is 6.0.0-BETA, 0.3.0 (I think) 1.18.2 (Fabric loader 1.14.7).

**Comment by LuciusofLegend** [comment]
I'm trying to test terra on its own (6.2.0, default, 1.19, 1.14.8) but it keeps giving me '[12:05:52] [main/WARN]: Failed to parse level-type terra:overworld, defaulting to minecraft:normal'.  Terra is the only mod in my mods folder, I left the config blank so that terra can generate it, and my server.properties are default except for 'level-type=terra/:OVERWORLD'.  I also deleted all other files (except for the server.jar and the mods folder).  Do you know what could have gone wrong?

These are the main/WARN messages I got:

[main/WARN]: Reference map 'terra.fabric.refmap.json' for terra.fabric.mixins.json could not be read. If this is a development environment you can ignore this message

[main/WARN]: Mod fabric-permissions-api-v0, version 0.1-SNAPSHOT does not follow semantic versioning specification, Terra addons will be unable to depend on it.

[main/WARN]: Failed to parse level-type terra:overworld, defaulting to minecraft:normal

**Comment by Roan-V** [comment]
level-type should be: terra:<config_if>/<config_id>
(for the default pack this would be terra:overworld/overworld)

**Comment by LuciusofLegend** [comment]
Thank you very much!

**Comment by LuciusofLegend** [comment]
In this configuration the kelp is generating as expected.  I'm currently deleting the world folder and adding in the other mods to see if the issue is a different mod, just the terra version, or world corruption.

**Comment by LuciusofLegend** [comment]
I'm not going to work on this at the moment.  I'll get back to figuring this out later today or tomorrow.

**Comment by LuciusofLegend** [comment]
Hi, this is simply a bug with the older version of terra I meantioned (6.0, 0.3.0), but it's fixed in the latest verison.  Thanks!
