### ISSUE TITLE
Dead Trees

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/TerraOverworldConfig#14]
Hand built and or procedural, comprising of just logs (strictly no fences, slabs, stairs, etc in trees!).

#### References

![image](https://user-images.githubusercontent.com/73215501/146276851-4d4d8c4d-84d9-4437-a9fa-487a835cc9d4.png)

![image](https://user-images.githubusercontent.com/73215501/146276882-fcbebcfb-65ea-4968-a00a-e5f4f3442ca8.png)

![image](https://user-images.githubusercontent.com/73215501/146276911-b34d0f7e-6850-43e5-89e6-5921505ed3d3.png)

**Comment by Sancires** [comment]
Closing as marked "Done"
