### ISSUE TITLE
Fix mushrooms using unused blockstates. (This causes issues with resource packs that use unused blockstates for custom blocks)

### ISSUE THREAD

**Issue by MagmaBro123** [PolyhedralDev/TerraOverworldConfig#147]
See https://canary.discord.com/channels/715448651786485780/1027352649365979216/1027352649365979216.

**Comment by Sancires** [comment]
Very late response, however this issue is a bit beyond the scope of our pack and is rather Bukkit specific. If you do use the block states id just recommend modifying the config for your server, as removing them all from the pack is a limitation that wont be relevant for a majority of users.
