### ISSUE TITLE
[Feature] Tree cutting compatibility

### ISSUE THREAD

**Issue by LuciusofLegend** [PolyhedralDev/TerraOverworldConfig#148]
### Pre-Request Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched github for similar features requests, including closed
  ones, and found none.
- [x] I believe this is within the scope of Terra.
- [x] This feature request is for *all* of Terra, and isn't something that
  should be implemented by a pack or addon.

## Feature Description

Better compatibility with mods like TreeFall or Trees Do Not Float

### What Problem Does This Solve?

When I use the mod TreeFall, it leaves leafs floating.

### A Solution You'd Like

If there is a way to make leaves from Terra trees decay like normal, that would solve the issue to a reasonable degree.

### Alternative Solutions

1.  I could open an issue with the creator of TreeCutter about this.
2.  You could also require all leaves in trees to be directly touching another leaf.

**Comment by Sancires** [comment]
Semi-alleviated
