### ISSUE TITLE
Jungle Biome

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/TerraOverworldConfig#15]
Generating in tropical areas of high precipitation, jungles are a class of rainforest that will consist of dense vegetation that will be difficult for players to traverse.
Variations can include flat jungles, mountainous jungles, bamboo jungles, etc. Mountainous jungles may contain less vegetation and more boulders. Jungle river variants may also act similarly to swamp biomes with trees emerging from under the water.

#### References

![image](https://user-images.githubusercontent.com/73215501/146277539-32879b2c-cf15-4b64-a012-2988a03d94be.png)

![image](https://user-images.githubusercontent.com/73215501/146277558-7259548e-7fe0-467f-a7b7-616fad42c9ca.png)

![image](https://user-images.githubusercontent.com/73215501/146277552-c997ed41-a433-47b7-a96a-1c47d1152c71.png)

![image](https://user-images.githubusercontent.com/73215501/146277569-7f1ad4a7-23f4-49d6-9c39-895227fdd91a.png)

**Comment by Sancires** [comment]
Closing as marked "Done"
