### ISSUE TITLE
Fix sculk generation in deep dark and ancient cities

### ISSUE THREAD

**Issue by Hexze** [PolyhedralDev/TerraOverworldConfig#152]
Sculk generation in the deep dark seems to be bugged- it often forms web-like structures across caves. Sometimes this actually generates some very cool looking environments, but it also ends up creating floating sculk in some areas.

![2023-08-30_23 22 54](https://github.com/PolyhedralDev/TerraOverworldConfig/assets/93348834/ee9060e5-57b1-4d01-8f2d-a022c4ff771b)
![2023-08-30_23 22 58](https://github.com/PolyhedralDev/TerraOverworldConfig/assets/93348834/a77dae41-04ca-4093-bcba-76c30b1feee3)

Additionally, this messes up ancient cities quite a lot. Some areas are obscured by sculk protrusions, and other very large areas of the city generate with no sculk cover at all, removing the challenge of the ancient city.

![2023-08-30_23 23 17](https://github.com/PolyhedralDev/TerraOverworldConfig/assets/93348834/30cebd6e-4bb9-4d18-83e8-a3b24ce49c87)
![2023-08-30_23 23 24](https://github.com/PolyhedralDev/TerraOverworldConfig/assets/93348834/4079100b-47ed-42d6-afc2-4b7bf3691862)
![2023-08-30_23 23 42](https://github.com/PolyhedralDev/TerraOverworldConfig/assets/93348834/42e794dc-1ad1-460f-81af-0fa1011a6f24)
![2023-08-30_23 23 59](https://github.com/PolyhedralDev/TerraOverworldConfig/assets/93348834/f05c3709-bd7a-4200-8576-af288737bd1b)

**Comment by Hexze** [comment]
Looking to create an SMP with this, so I'd appreciate it if you could get back to me! If it's a quick fix, I'll wait to launch the SMP til' the issue is gone- if not, this bug is a small price to pay for the beautiful surface generation :)

**Comment by Astrashh** [comment]
The webs are intentional, if you don't want them follow this guide http://terra.polydev.org/config/development/modifying-existing-pack.html and delete this line https://github.com/PolyhedralDev/TerraOverworldConfig/blob/master/biomes/cave/deep_dark.yml#L13

**Comment by Hexze** [comment]
I see, thank you.

What about the large areas of ancient cities with no sculk? Will increasing the frequency of sculk patches help with this?

**Comment by Hexze** [comment]
Nevermind- unless I'm missing something this seems to be a separate issue. Increasing the frequency of various sculk features does nothing to the ancient city. Only sculk that is part of the structure itself generates.

**Comment by Hexze** [comment]
Nevermind- the issue here is that the ancient city is not entirely covered in the deep dark biome. Instead of the entire area being contained in the deep dark biome, Various surface biomes are interrupting the outer areas of the city. The center seems to generate correctly in each city I've found.
