### ISSUE TITLE
Monster Room (Dungeon) Generation ?

### ISSUE THREAD

**Issue by cellophane303** [PolyhedralDev/TerraOverworldConfig#155]
Does Terra affect [Monster Room](https://minecraft.fandom.com/wiki/Monster_Room) generation?  I've started two worlds and even after flying around in spectator I haven't found any monster rooms.  Looking at a typical seed in Chunkbase they are pretty common, so I find it odd that there aren't any generated in Terra.  I've tried this in 1.20.1 and 1.20.2 and haven't found nay spawners, other than the cave spider spawners in mineshafts.

**Comment by Sancires** [comment]
To be added in 2.0

**Comment by cellophane303** [comment]
Thanks =)

**Comment by Sancires** [comment]
PR is currently open and will be merged.

**Comment by Sancires** [comment]
This was added to the 2.0 branch & will likely be backported to 1.4
