### ISSUE TITLE
Most biomes lack palette for underwater sections

### ISSUE THREAD

**Issue by dfsek** [PolyhedralDev/TerraOverworldConfig#19]
In some biomes, this is immediately apparent because they contain small amounts of water:
![image](https://user-images.githubusercontent.com/39248502/147867709-3762ed82-2240-4981-bd3c-1224b67fc620.png)

In others it isn't obvious until bordering a biome like River:
![image](https://user-images.githubusercontent.com/39248502/147867749-14fc2278-bae6-4037-9acb-3c87e31aa9c6.png)

**Comment by Astrashh** [comment]
Fixed in 640b1b439780a797aa030d636e8aee3228a023d7
