### ISSUE TITLE
Create Lush biomes?

### ISSUE THREAD

**Issue by Jason-Ding19** [PolyhedralDev/TerraOverworldConfig#22]
Felt like Lush biomes weren't implemented much so I'd like to propose some sort of Lush biome. Would be cool to have an aboveground version of Lush Caves like the biome I did in the past (Lush Jungles, images [here](https://imgur.com/a/xUg6If3)), so that there's a biome for players to obtain all of the Lush related blocks in an actual Lush themed biome, if you understand what I mean.

**Comment by Sancires** [comment]
Humid and Semi-Humid Tropical and Subtropical biomes fill this role.
