### ISSUE TITLE
Arid Savanna Biome

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/TerraOverworldConfig#5]
Basic version of a savanna similar to the vanilla savanna biome.

Multiple variants can be made for different elevation zones:
- Flat
- Small Hills
- Large Hills
- Small Mountains

Arid savannas should be distributed in tropical and subtropical temperature zones, as an intermediary between deserts and more humid tropical biomes such as jungle / rainforest.

#### References

![image](https://user-images.githubusercontent.com/73215501/146156095-4b3cf27e-41dd-4069-97f5-ffd261b4ed6d.png)

![image](https://user-images.githubusercontent.com/73215501/146156664-470f8235-0ff5-4bea-bcdc-e608376c75d8.png)

**Comment by Sancires** [comment]
Closing as marked "Done"
